# Generated by Django 5.0.4 on 2024-05-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='cards',
            field=models.ManyToManyField(related_name='tags', to='flashcards_app.card'),
        ),
    ]
