# Generated by Django 5.0.4 on 2024-06-20 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards_app', '0008_alter_card_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='user',
        ),
    ]
